# author: Kamil Król

include("functions.jl")
using .functions

delta = 1e-5
epsilon = 1e-5
max_iterations = 40

f1(x) = MathConstants.e^(1.0 - x) - 1.0
f2(x) = x * MathConstants.e^(-x)

f1′(x) = -MathConstants.e^(1.0 - x)
f2′(x) = MathConstants.e^-x - x * MathConstants.e^-x

# functions = [(f1, f1′,"f1:"), (f2, f2′,"f2:")]

println("f1:")
println("Bisection method:")
root, value, iterations, error = mbisekcji(f1, 0.0, 2.0, delta, epsilon)
# println("root: $root, value: $value, number of iterations: $iterations, error: $error")
println("[0.0, 2.0] & $root & $value & $iterations \\\\ \\hline")
root, value, iterations, error = mbisekcji(f1, 0.4, 2.4, delta, epsilon)
# println("root: $root, value: $value, number of iterations: $iterations, error: $error")
println("[0.4, 2.4] & $root & $value & $iterations \\\\ \\hline")
root, value, iterations, error = mbisekcji(f1, -10.0, 25.0, delta, epsilon)
# println("root: $root, value: $value, number of iterations: $iterations, error: $error")
println("[-10.0, 25.0] & $root & $value & $iterations \\\\ \\hline")
root, value, iterations, error = mbisekcji(f1, -450.0, 500.0, delta, epsilon)
# println("root: $root, value: $value, number of iterations: $iterations, error: $error")
println("[-450.0, 500.0] & $root & $value & $iterations \\\\ \\hline")
root, value, iterations, error = mbisekcji(f1, -10000.0, 10000.0, delta, epsilon)
# println("root: $root, value: $value, number of iterations: $iterations, error: $error")
println("[-10000.0, 10000.0] & $root & $value & $iterations \\\\ \\hline")

println("Newton method:")
root, value, iterations, error = mstycznych(f1, f1′, 1.5, delta, epsilon, max_iterations)
# println("root: $root, value: $value, number of iterations: $iterations, error: $error")
println("1.5 & $root & $value & $iterations \\\\ \\hline")
root, value, iterations, error = mstycznych(f1, f1′, 3.0, delta, epsilon, max_iterations)
# println("root: $root, value: $value, number of iterations: $iterations, error: $error")
println("3.0 & $root & $value & $iterations & $error\\\\ \\hline")

println("Secant method:")
root, value, iterations, error = msiecznych(f1, 1.5, 2.0, delta, epsilon, max_iterations)
# println("root: $root, value: $value, number of iterations: $iterations, error: $error")
println("1.5 & 2.0 & $root & $value & $iterations \\\\ \\hline")
root, value, iterations, error = msiecznych(f1, 1.0, 6.5, delta, epsilon, max_iterations)
# println("root: $root, value: $value, number of iterations: $iterations, error: $error")
println("1.0 & 6.5 & $root & $value & $iterations \\\\ \\hline")
root, value, iterations, error = msiecznych(f1, -3.0, 4.0, delta, epsilon, max_iterations)
# println("root: $root, value: $value, number of iterations: $iterations, error: $error")
println("-3.0 & 4.0 & $root & $value & $iterations \\\\ \\hline")
root, value, iterations, error = msiecznych(f1, 10.0, 40.0, delta, epsilon, max_iterations)
# println("root: $root, value: $value, number of iterations: $iterations, error: $error")
println("10.0 & 40.0 & $root & $value & $iterations \\\\ \\hline")
root, value, iterations, error = msiecznych(f1, -1.0, -0.5, delta, epsilon, max_iterations)
# println("root: $root, value: $value, number of iterations: $iterations, error: $error")
println("-1.0 & -0.5 & $root & $value & $iterations \\\\ \\hline")
root, value, iterations, error = msiecznych(f1, -1.0, 6.0, delta, epsilon, max_iterations)
# println("root: $root, value: $value, number of iterations: $iterations, error: $error")
println("-1.0 & 60.0 & $root & $value & $iterations \\\\ \\hline")
println("---------------------------------------------")

println("f2:")
println("Bisection method:")
root, value, iterations, error = mbisekcji(f2, -1.0, 2.0, delta, epsilon)
# println("root: $root, value: $value, number of iterations: $iterations, error: $error")
println("[-1.0, 2.0] & $root & $value & $iterations \\\\ \\hline")
root, value, iterations, error = mbisekcji(f2, -10.0, 25.0, delta, epsilon)
# println("root: $root, value: $value, number of iterations: $iterations, error: $error")
println("[-10.0, 25.0] & $root & $value & $iterations \\\\ \\hline")
root, value, iterations, error = mbisekcji(f2, -450.0, 500.0, delta, epsilon)
# println("root: $root, value: $value, number of iterations: $iterations, error: $error")
println("[-450.0, 500.0] & $root & $value & $iterations \\\\ \\hline")
root, value, iterations, error = mbisekcji(f2, -10000.0, 12000.0, delta, epsilon)
# println("root: $root, value: $value, number of iterations: $iterations, error: $error")
println("[-10000.0, 12000.0] & $root & $value & $iterations \\\\ \\hline")

println("Newton method:")
root, value, iterations, error = mstycznych(f2, f2′, -2.0, delta, epsilon, max_iterations)
# println("root: $root, value: $value, number of iterations: $iterations, error: $error")
println("-2.0 & $root & $value & $iterations \\\\ \\hline")

println("Secant method:")
root, value, iterations, error = msiecznych(f2, -1.0, -0.5, delta, epsilon, max_iterations)
# println("root: $root, value: $value, number of iterations: $iterations, error: $error")
println("-1.0 & -0.5 & $root & $value & $iterations \\\\ \\hline")
root, value, iterations, error = msiecznych(f2, -2.0, 5.0, delta, epsilon, max_iterations)
# println("root: $root, value: $value, number of iterations: $iterations, error: $error")
println("-2.0 & 5.0 & $root & $value & $iterations \\\\ \\hline")
root, value, iterations, error = msiecznych(f2, 1.0, 6.5, delta, epsilon, max_iterations)
# println("root: $root, value: $value, number of iterations: $iterations, error: $error")
println("1.0 & 6.5 & $root & $value & $iterations \\\\ \\hline")
root, value, iterations, error = msiecznych(f2, 10.0, 40.0, delta, epsilon, max_iterations)
# println("root: $root, value: $value, number of iterations: $iterations, error: $error")
println("10.0 & 40.0 & $root & $value & $iterations \\\\ \\hline")
root, value, iterations, error = msiecznych(f2, -17.0, 0.5, delta, epsilon, max_iterations)
# println("root: $root, value: $value, number of iterations: $iterations, error: $error")
println("-17.0 & 0.5 & $root & $value & $iterations \\\\ \\hline")
println("---------------------------------------------")

println("other tests:")
println("Newton method (f2) x0=5.0:")
root, value, iterations, error = mstycznych(f2, f2′, 5.0, delta, epsilon, max_iterations)
# println("root: $root, value: $value, number of iterations: $iterations, error: $error")
println("$root & $value & $iterations & $error\\\\ \\hline")

println("Newton method (f2) x0=1.0:")
root, value, iterations, error = mstycznych(f2, f2′, 1.0, delta, epsilon, max_iterations)
# println("root: $root, value: $value, number of iterations: $iterations, error: $error")
println("$root & $value & $iterations & $error\\\\ \\hline")
